apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-writer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s3-writer
  template:
    metadata:
      labels:
        app: s3-writer
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: app
          image: 537940551831.dkr.ecr.us-east-1.amazonaws.com/s3-write-test:latest
          ports:
            - containerPort: 3000
          env:
            - name: S3_BUCKET
              value: kiet-test-bucket18
---
apiVersion: v1
kind: Service
metadata:
  name: s3-writer-svc
spec:
  selector:
    app: s3-writer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: s3-writer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: s3-writer
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
